---
endpoint: host
host: traefik.example.com
self_cert: true
# global: delete characters across whole line, not just first one
scheme: https
# what 'using' parameter for router will be
# if multiple available, will use 'prefer'red protocol
protocols:
  websecure: https
  web: http
# if more than one scheme available
# not currently used
prefer: websecure
# Use refresh header to auto refresh web page
refresh: true
refresh_interval: 300
bind_port: 8081
bind_ip: 0.0.0.0
# open links in new window
new_window: true
filters:
  - op: deleteline
    regex: '\|\|'
  - op: select
    regex: 'Host\(`([^`]+)`\)'
    global: true
  - op: deleteline
    regex: HostRegexp
