---
endpoint: hobbes
host: traefik.riffraff169.org
https: true
self_cert: true
# global: delete characters across whole line, not just first one
filters:
  - op: deleteline
    regex: '\|\|'
  - op: select
    regex: 'Host\(`([^`]+)`\)'
    global: true
#  - op: delete
#    regex: '`)"'
#    global: true
  - op: deleteline
    regex: HostRegexp
#  - op: delete
#    regex: '"'
#    global: true
