---
endpoint: hobbes
host: traefik.riffraff169.org
self_cert: true
# global: delete characters across whole line, not just first one
scheme: https
# what 'using' parameter for router will be
using_https: websecure
using_http: web
# if more than one scheme available
using_prefer: websecure
filters:
  - op: deleteline
    regex: '\|\|'
  - op: select
    regex: 'Host\(`([^`]+)`\)'
    global: true
#  - op: delete
#    regex: '`)"'
#    global: true
  - op: deleteline
    regex: HostRegexp
#  - op: delete
#    regex: '"'
#    global: true
